# Generated by Django 4.1.5 on 2023-01-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('is_staffed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('salary', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='personal.department')),
            ],
        ),
    ]
